server:
  port: 8081


#mybatis:
#  type-aliases-package: com.reward.dao
#  config-locations: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml

#正式环境数据库
#spring:
#  datasource:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.30.248.21:3306/reward?characterEncoding=utf8
#      username: dev
#      password: DEV

#使用h2数据库
#spring:
#  datasource:
#      driverClassName: org.h2.Driver
#      schema: classpath:db.sql/create-db.sql
#      data: classpath:db.sql/insert-data.sql
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  redis:
#    host: 127.0.0.1
#    database: 1
#    password: 123456
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-wait: -1
#      max-idle: 8
#    port: 6379
#    timeout: 50000


#可以自定义日志路径
#logging.config=classpath:logback.xml
#logging.path=/workspace/rock/jpa-test/log

#spring.redis.database=1
##redis服务器名称
#spring.redis.host=127.0.0.1
##redis服务器密码
#spring.redis.password=123456
##redis服务器连接端口号
#spring.redis.port=6379
##redis连接池设置
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
##spring.redis.sentinel.master=
##spring.redis.sentinel.nodes=
#spring.redis.timeout=60000
